using System;
using Optimization.Base;

namespace Optimization.Genetic
{
    /// <summary>
    /// Chromosome class for genetic optimization.
    /// Initialized with random values generated by GeneFactory randomization methods.
    /// </summary>
    [Serializable]
    public sealed class ChromosomeRandom: Chromosome
    {
        /// <summary>
        /// Creates randomly generated chromosome
        /// </summary>
        /// <param name="configArray">Gene configurations array</param>
        /// <param name="length">Chromosome length</param>
        public ChromosomeRandom(GeneConfiguration[] configArray, int length) : base(configArray, length)
        {
            // fill the gene array with generated values
            for (var i = 0; i < GeneConfigurationArray.Length; i++)
            {
                ReplaceGene(i, GenerateGene(i));
            }
        }

        /// <summary>
        /// Generates the gene for the specified index.
        /// </summary>
        /// <param name="geneIndex">Gene index.</param>
        /// <returns>The gene generated at the specified index.</returns>
        public override Gene GenerateGene(int geneIndex)
        {
            // Get Gene configuration ->
            var configuration = GeneConfigurationArray[geneIndex];

            // Generate random within min-max boundaries ->
            return GeneFactory.GenerateRandom(configuration);
        }
    }

}
